# Generated by Django 3.0.2 on 2020-03-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
