# Generated by Django 3.0.2 on 2020-03-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_auto_20200227_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_prescription',
            name='file_name',
            field=models.CharField(default='Some Name', max_length=15),
        ),
        migrations.AddField(
            model_name='upload_reports',
            name='file_name',
            field=models.CharField(default='Some Name', max_length=15),
        ),
        migrations.AlterField(
            model_name='upload_prescription',
            name='prescription_file',
            field=models.FileField(default='Some File', upload_to='files/prescriptions'),
        ),
        migrations.AlterField(
            model_name='upload_reports',
            name='report_file',
            field=models.FileField(default='Some File', upload_to='files/reports'),
        ),
    ]
