# Generated by Django 3.0.2 on 2020-03-08 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0007_auto_20200306_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_prescription',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='upload_reports',
            name='file_name',
        ),
        migrations.AddField(
            model_name='upload_prescription',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='upload_reports',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
