# Generated by Django 3.0.2 on 2020-02-23 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='disease_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
