# Generated by Django 3.0.2 on 2020-02-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20200223_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='time',
        ),
    ]
