# Generated by Django 3.0.2 on 2020-02-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_remove_upload_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Prescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostics_name', models.CharField(max_length=50)),
                ('report_type', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
