# Generated by Django 3.0.2 on 2020-02-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_upload_prescriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='prescription_file',
            field=models.FileField(default='Some File', upload_to='files/prescriptions/'),
        ),
        migrations.AddField(
            model_name='upload_prescriptions',
            name='report_file',
            field=models.FileField(default='Some File', upload_to='files/reports/'),
        ),
    ]
